#!/usr/bin/env python3
"""Scaffold conservative UK/RHD BMW, MINI, Mercedes-Benz and Smart research records."""
from __future__ import annotations
import argparse, json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]; TODAY="2026-07-18"
CONFIG={
"bmw":{"name":"BMW","source":"https://www.bmw.co.uk/en_GB/all-models.html","manuals":"https://www.bmw.co.uk/en_GB/topics/owners/bmw-owners-manual.html","models":"1_series|1 Series;2_series|2 Series;3_series|3 Series;4_series|4 Series;5_series|5 Series;6_series|6 Series;7_series|7 Series;8_series|8 Series;x1|X1;x2|X2;x3|X3;x4|X4;x5|X5;x6|X6;x7|X7;z3|Z3;z4|Z4;i3|i3;i4|i4;i5|i5;i7|i7;i8|i8;ix|iX;ix1|iX1;ix2|iX2;ix3|iX3;m2|M2;m3|M3;m4|M4;m5|M5;m6|M6;m8|M8;xm|XM","systems":"EWS, CAS, FEM, BDC and later BDC generations are generation/fitted-hardware dependent"},
"mini":{"name":"MINI","source":"https://www.mini.co.uk/en_GB/home/range/browse.html","manuals":"https://www.mini.co.uk/en_GB/home/owners/drivers-guide-and-owners-information.html","models":"hatch_3_door|Hatch 3-Door;hatch_5_door|Hatch 5-Door;convertible|Convertible;clubman|Clubman;countryman|Countryman;coupe|Coupé;roadster|Roadster;paceman|Paceman;aceman|Aceman","systems":"BMW Group EWS/CAS/FEM/BDC-derived architecture varies by MINI generation and fitted hardware"},
"mercedes_benz":{"name":"Mercedes-Benz","source":"https://www.mercedes-benz.co.uk/passengercars/models.html","manuals":"https://www.mercedes-benz.co.uk/passengercars/services/manuals.html","models":"a_class|A-Class;b_class|B-Class;c_class|C-Class;e_class|E-Class;s_class|S-Class;cla|CLA;cls|CLS;cle|CLE;clk|CLK;clc|CLC;slk|SLK;slc|SLC;sl|SL;amg_gt|AMG GT;gla|GLA;glb|GLB;glc|GLC;glk|GLK;gle|GLE;m_class|M-Class;gls|GLS;gl_class|GL-Class;g_class|G-Class;v_class|V-Class;vito|Vito;sprinter|Sprinter;citan|Citan;eqa|EQA;eqb|EQB;eqc|EQC;eqe|EQE;eqe_suv|EQE SUV;eqs|EQS;eqs_suv|EQS SUV;eqv|EQV;x_class|X-Class","systems":"DAS/FBS generation, EIS/EZS, ESL/ELV and key type require exact chassis and fitted-hardware evidence"},
"smart":{"name":"Smart","source":"https://uk.smart.com/en/models/","manuals":"https://uk.smart.com/en/service/manuals/","models":"city_coupe|City-Coupé;fortwo|fortwo;forfour|forfour;roadster|Roadster;smart_1|#1;smart_3|#3;smart_5|#5","systems":"Legacy Mercedes-derived and current smart EV access architectures must not be conflated"}}

def write(p,d): p.parent.mkdir(parents=True,exist_ok=True); p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+"\n",encoding="utf-8")
def pairs(spec): return [tuple(x.split("|",1)) for x in spec.split(";")]
def create(mid,name,cfg,base):
 f={x:f"{x}.json" for x in ("models","procedures","modules","wiring","service_functions","notes","photos")}; pub=cfg["name"]
 write(base/mid/"manifest.json",{"schema_version":"2.1","updated_at":TODAY,"manufacturer":{"id":base.name,"name":pub},"model":{"id":mid,"name":name},"version":1,"files":f,"verification":{"status":"research_in_progress","market":"UK","drive_side":"RHD"}})
 write(base/mid/"models.json",{"schema_version":"2.1","model":name,"market":"UK","drive_side":"RHD","generations":[{"id":mid+"_uk_scope","name":name+" UK-market generations","years":"Generation/build-date specific; verify by VIN","platform":"Exact chassis/platform requires generation confirmation","immobiliser_family":cfg["systems"],"key_variants":[{"type":"keyed","status":"research_required"},{"type":"slot_key","status":"research_required"},{"type":"proximity","status":"research_required"},{"type":"keyless","status":"research_required"}],"status":"partially_verified"}],"sources":{"official_uk_range":{"publisher":pub+" UK","url":cfg["source"],"checked_at":TODAY,"confidence":"high","supports":["UK model-family presence"]},"official_manuals":{"publisher":pub+" UK","url":cfg["manuals"],"checked_at":TODAY,"confidence":"high","supports":["VIN/generation-specific documentation requirement"]}}})
 procs=[]
 for route in ("keyed","slot_key","proximity","keyless"):
  procs += [{"id":"add_key_"+route,"name":"Add key - "+route.replace("_"," "),"method":"No chassis-specific supported method recorded","status":"research_required"},{"id":"akl_"+route,"name":"All keys lost - "+route.replace("_"," "),"method":"No chassis-specific supported method recorded","status":"research_required"}]
 write(base/mid/"procedures.json",{"schema_version":"2.1","model":name,"procedures":procs})
 write(base/mid/"modules.json",{"schema_version":"2.1","model":name,"modules":[{"id":"immobiliser_authorisation","name":"Immobiliser/start-authorisation controller","role":"Identify by VIN, chassis and module part number","location":"UK RHD location not verified","status":"research_required"},{"id":"steering_lock","name":"Electronic steering lock where fitted","role":"Variant-specific; mechanical and electronic arrangements kept separate","location":"UK RHD location not verified","status":"research_required"},{"id":"gateway_body","name":"Gateway/body-domain controller","role":"Security role requires exact architecture evidence","location":"UK RHD location not verified","status":"research_required"}]})
 write(base/mid/"wiring.json",{"schema_version":"2.1","model":name,"connections":[{"id":"obd","name":"OBD-II connector","location":"UK RHD location not verified","status":"research_required"},{"id":"bench","name":"Bench connection","notes":"No pinout, EEPROM, MCU, processor, adapter or wiring claim is inferred from a system-family match.","status":"research_required"}]})
 write(base/mid/"service_functions.json",{"schema_version":"2.1","model":name,"functions":[{"id":"key_learning","name":"Key learning","availability":"Exact chassis, system and tool dependent","status":"research_required"},{"id":"module_replacement","name":"Immobiliser-related module replacement","availability":"Online/offline requirements not verified","status":"research_required"}]})
 write(base/mid/"notes.json",{"schema_version":"2.1","model":name,"notes":[{"title":"Architecture boundary","text":cfg["systems"]+". No procedure is inherited solely from a shared family label."},{"title":"Variant policy","text":"Keyed, slot-key, proximity and keyless routes remain separate; non-applicable routes require generation evidence before closure."},{"title":"Evidence needed","text":"Record VIN/build date, chassis code, key and module part numbers, UK RHD locations, tool/version and successful job result."}],"status":"research_in_progress"})
 write(base/mid/"photos.json",{"schema_version":"2.1","model":name,"photos":[],"required":["UK RHD OBD location","Start-authorisation and steering-lock modules","Each fitted key variant and part number"],"status":"awaiting_verified_images"})
def main():
 a=argparse.ArgumentParser(); a.add_argument("manufacturer",choices=CONFIG); k=a.parse_args().manufacturer; c=CONFIG[k]; base=ROOT/"database"/"vehicles"/k; ms=pairs(c["models"])
 for mid,n in ms:create(mid,n,c,base)
 write(base/"manifest.json",{"schema_version":"2.1","updated_at":TODAY,"manufacturer":{"id":k,"name":c["name"],"market":"UK","drive_side":"RHD"},"version":1,"models":{mid:{"name":n,"version":1,"manifest":mid+"/manifest.json","status":"research_in_progress"} for mid,n in ms},"status":"research_in_progress","sources":{"official_uk_range":{"url":c["source"]},"official_manuals":{"url":c["manuals"]}}})
 for p in (ROOT/"manifest.json",ROOT/"database"/"manifest.json"):
  d=json.loads(p.read_text(encoding="utf-8")); d["manufacturers"][k]={"name":c["name"],"version":1,"manifest":f"database/vehicles/{k}/manifest.json","status":"research_in_progress","updated_at":TODAY}; write(p,d)
 print(f"created {c['name']} UK batch ({len(ms)} models)")
if __name__=="__main__":main()
